name: Greetings

on: [ pull_request_target, issues ]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Thank you for your first issue on this project, pls. continue with your enthusiasm. We will work on you're issue."
          pr-message: "Thank you for your first PR on this project, pls. continue you're enthusiasm. We will work on you're PR."
