# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '21 21 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: 'Long time nobody showed activity here. We will add the "Stale Label" to your issue.'
          stale-pr-message: 'Long time nobody showed activity here. We will add the "Stale Label" to your PR.'
          stale-issue-label: 'stale-issue'
          stale-pr-label: 'stale-pr'
